# Generated by Django 4.2.4 on 2023-08-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_app', '0002_alter_user_invited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_privileged',
            field=models.BooleanField(default=False, verbose_name='Привилегированный доступ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=32, unique=True, verbose_name='Номер телефона'),
        ),
    ]
