# Generated by Django 4.2.4 on 2023-08-21 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referral_app', '0004_rename_invite_code_user_invitation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='invited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='referral_app.user'),
        ),
    ]
